### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by ScumbagDog** [cody2007/arcane_fortune#1]
There are two license notices currently - one in license.txt (AGPL) and one in contributing.txt (looks like an MIT-style license). Would you mind clarifying which is currently the license for Arcane Fortune?

**Comment by cody2007** [comment]
I release Arcane Fortune, ironnetpro, and the sdl code under the AGPL version-3-or-later.

I only ask if you'd like to contribute to this repository that you license your contributions under the MIT-style license I included in the contributing file.

I have seen other GPL projects on Steam ask for full copyright from contributors (https://git.net-core.org/tome/t-engine4/blob/master/CONTRIBUTING), because, as I mentioned in the contributing file the GPL is incompatible with Steam.

I like the idea of the MIT license better because it means you can be legally assured I'll credit you if I use your contributions.

**Comment by ScumbagDog** [comment]
That's entirely fair, albeit a bit confusing. Personally I'd prefer just having one license (even if it means signing off my own right to my contributions to you), just because it is simpler to understand, but it is obviously your call.

**Comment by cody2007** [comment]
I appreciate your understanding. I updated the contributing file to give people that option -- and also wrote up a short summary of another reason why signing over copyright could be preferred (provided one cares about the project being copy-left).

Unrelated, but is there something you're interested in getting involved with with the project? Or just looking around? :)

**Comment by ScumbagDog** [comment]
I might contribute if I find the time, but time is already in short supply, and I won't commit myself if I can't fulfill that commitment.

But also because I found a repo of [awesome rust projects](https://github.com/rust-unofficial/awesome-rust), and when I tried adding Arcane fortune to that list, one of the collaborators pointed out the license and build problems as concerning.

**Comment by cody2007** [comment]
I see, thanks for doing that. Let me know if you have other issues or questions in the future.
